version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: pizza_admin
      POSTGRES_PASSWORD: geheim123
      POSTGRES_DB: pizzashop
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
